go-rest-1:
  image: juanjoqmelian/users
  ports:
   - "8080:8080"
  links:
   - mongodb:local-mongo
go-rest-2:
  image: juanjoqmelian/users
  ports:
   - "8081:8080"
  links:
   - mongodb:local-mongo
go-rest-3:
  image: juanjoqmelian/users
  ports:
   - "8082:8080"
  links:
   - mongodb:local-mongo
mongodb:
  image: mongo
  ports:
     - "27017:27017"